### ISSUE TITLE
“BatchPrefillWithPagedKVCache failed with error an illegal memory access was encountered” when I use a cuda that is not `cuda:0`

### ISSUE THREAD

**Issue by wfloveiu** [flashinfer-ai/flashinfer#924]
When I use `cuda:0`, there is no error log. when I use `cuda:1` to do `BatchPrefillWithPagedKVCache`, It gives an error
`BatchPrefillWithPagedKVCache failed with error an illegal memory access was encountered`
Here is the whole log: 
```
CUDA Error: an illegal memory access was encountered (700) /app/include/flashinfer/attention/prefill.cuh: line 2340 at function cudaLaunchKernel((void*)kernel, nblks, nthrs, args, smem_size, stream)
Traceback (most recent call last):
  File "/home/wufang/channel_sparsity/PSCache/test/test.py", line 57, in <module>
    generate(model, tokenizer)
  File "/home/wufang/channel_sparsity/PSCache/test/test.py", line 25, in generate
    output = model.generate(input_batch, do_sample=True, max_new_tokens=10*1024-4096, use_cache=True)[0]
  File "/mnt/wufang/anaconda3/envs/PRCache/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/wufang/anaconda3/envs/PRCache/lib/python3.10/site-packages/transformers/generation/utils.py", line 2047, in generate
    result = self._sample(
  File "/mnt/wufang/anaconda3/envs/PRCache/lib/python3.10/site-packages/transformers/generation/utils.py", line 3007, in _sample
    outputs = self(**model_inputs, return_dict=True)
  File "/mnt/wufang/anaconda3/envs/PRCache/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/mnt/wufang/anaconda3/envs/PRCache/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wufang/channel_sparsity/PSCache/source/pscache/model/Attention.py", line 173, in _new_self_forward
    ret = _old_self_forward(*args, **kwargs)
  File "/mnt/wufang/anaconda3/envs/PRCache/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1189, in forward
    outputs = self.model(
  File "/mnt/wufang/anaconda3/envs/PRCache/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/mnt/wufang/anaconda3/envs/PRCache/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/wufang/anaconda3/envs/PRCache/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1000, in forward
    layer_outputs = decoder_layer(
  File "/mnt/wufang/anaconda3/envs/PRCache/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/mnt/wufang/anaconda3/envs/PRCache/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/wufang/anaconda3/envs/PRCache/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 729, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/mnt/wufang/anaconda3/envs/PRCache/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/mnt/wufang/anaconda3/envs/PRCache/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wufang/channel_sparsity/PSCache/source/pscache/model/Attention.py", line 148, in <lambda>
    lambda mod: lambda *args, **kwargs: attention_forward(
  File "/home/wufang/channel_sparsity/PSCache/source/pscache/model/Attention.py", line 76, in attention_forward
    attn_output = infer_state.batch_prefill_attention(layer_idx, query_states)
  File "/home/wufang/channel_sparsity/PSCache/source/pscache/infer_state.py", line 295, in batch_prefill_attention
    return self.prefill_handler._run(q, kvc.c2p,  kvc.buffer)
  File "/home/wufang/channel_sparsity/PSCache/source/pscache/kernels.py", line 173, in _run
    return self.run(q, paged_kv_cache)
  File "/mnt/wufang/anaconda3/envs/PRCache/lib/python3.10/site-packages/flashinfer/prefill.py", line 1679, in run
    self._cached_module.paged_run(*run_args)
  File "/mnt/wufang/anaconda3/envs/PRCache/lib/python3.10/site-packages/flashinfer/prefill.py", line 346, in paged_run
    paged_run_func(
  File "/mnt/wufang/anaconda3/envs/PRCache/lib/python3.10/site-packages/torch/_ops.py", line 1116, in __call__
    return self._op(*args, **(kwargs or {}))
  File "/mnt/wufang/anaconda3/envs/PRCache/lib/python3.10/site-packages/torch/utils/_device.py", line 106, in __torch_function__
    return func(*args, **kwargs)
  File "/mnt/wufang/anaconda3/envs/PRCache/lib/python3.10/site-packages/torch/_ops.py", line 1116, in __call__
    return self._op(*args, **(kwargs or {}))
RuntimeError: BatchPrefillWithPagedKVCache failed with error an illegal memory access was encountered
```

Below is my envs:
```
A100 80G * 8
flashinfer-python        0.2.2.post1+cu124torch2.5
torch                           2.5.1+cu124
```

**Comment by rothn** [comment]
I am also having this issue with Qwen 1.5B trained on TRL and HuggingFace TGI 3.1.1 for GCP. This Docker build might help for reproducing the issue. Note that DeepSeek Qwen 7B works fine.

Environment variables:
```
          "NUM_SHARD": "1",
          "MAX_INPUT_TOKENS": "512",
          "MAX_TOTAL_TOKENS": "1024",
          "MAX_BATCH_PREFILL_TOKENS": "1512",
          "CUDA_LAUNCH_BLOCKING": "1", # Debug for Qwen 1.5B
          "TORCH_USE_CUDA_DSA": "1",   # Debug for Qwen 1.5B
```

Note that AIP_STORAGE_URI is just a Google Cloud Storage path to the model (much like s3 on AWS, but for Google Cloud).

I'm including the exact Docker resources I used to reproduce the issue, but they are based on the Dockerfile in https://github.com/huggingface/text-generation-inference , version-locked at 3.1.1.

entrypoint.sh
```
#!/bin/bash

# Check if MODEL_ID starts with "gcs://"
if [[ $AIP_STORAGE_URI == gs://* ]]; then
    echo "AIP_STORAGE_URI set and starts with 'gs://', proceeding to download from GCS."
    echo "AIP_STORAGE_URI: $AIP_STORAGE_URI"

    # Define the target directory
    TARGET_DIR="/tmp/model"
    mkdir -p "$TARGET_DIR"

    # Use gsutil to copy the content from GCS to the target directory
    echo "Running: gcloud storage storage cp $AIP_STORAGE_URI/* $TARGET_DIR --recursive"
    gcloud storage cp "$AIP_STORAGE_URI/*" "$TARGET_DIR" --recursive

    # Check if gsutil command was successful
    if [ $? -eq 0 ]; then
        echo "Model downloaded successfully to ${TARGET_DIR}."
        # Update MODEL_ID to point to the local directory
        echo "Updating MODEL_ID to point to the local directory."
        export MODEL_ID="$TARGET_DIR"
    else
        echo "Failed to download model from GCS."
        exit 1
    fi
fi

ldconfig 2>/dev/null || echo 'unable to refresh ld cache, not a big deal in most cases'

exec text-generation-launcher $@
```

Dockerfile
```
# Fetch and extract the TGI sources
FROM alpine AS tgi
RUN mkdir -p /tgi
ADD https://github.com/huggingface/text-generation-inference/archive/refs/tags/v3.1.1.tar.gz /tgi/sources.tar.gz
RUN tar -C /tgi -xf /tgi/sources.tar.gz --strip-components=1

# Rust builder
FROM lukemathwalker/cargo-chef:latest-rust-1.85.0 AS chef
WORKDIR /usr/src

ARG CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse

FROM chef AS planner
COPY --from=tgi /tgi/Cargo.lock Cargo.lock
COPY --from=tgi /tgi/Cargo.toml Cargo.toml
COPY --from=tgi /tgi/rust-toolchain.toml rust-toolchain.toml
COPY --from=tgi /tgi/proto proto
COPY --from=tgi /tgi/benchmark benchmark
COPY --from=tgi /tgi/router router
COPY --from=tgi /tgi/backends backends
COPY --from=tgi /tgi/launcher launcher

RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    python3.11-dev
RUN PROTOC_ZIP=protoc-21.12-linux-x86_64.zip && \
    curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v21.12/$PROTOC_ZIP && \
    unzip -o $PROTOC_ZIP -d /usr/local bin/protoc && \
    unzip -o $PROTOC_ZIP -d /usr/local 'include/*' && \
    rm -f $PROTOC_ZIP

COPY --from=planner /usr/src/recipe.json recipe.json
RUN cargo chef cook --profile release-opt --recipe-path recipe.json

COPY --from=tgi /tgi/Cargo.lock Cargo.lock
COPY --from=tgi /tgi/Cargo.toml Cargo.toml
COPY --from=tgi /tgi/rust-toolchain.toml rust-toolchain.toml
COPY --from=tgi /tgi/proto proto
COPY --from=tgi /tgi/benchmark benchmark
COPY --from=tgi /tgi/router router
COPY --from=tgi /tgi/backends backends
COPY --from=tgi /tgi/launcher launcher
RUN cargo build --profile release-opt --features google --frozen

# Python builder
# Adapted from: https://github.com/pytorch/pytorch/blob/master/Dockerfile
FROM nvidia/cuda:12.4.1-devel-ubuntu22.04 AS pytorch-install
WORKDIR /usr/src/

ARG PYTORCH_VERSION=2.6
ARG PYTHON_VERSION=3.11
# Keep in sync with `server/pyproject.toml`
ARG CUDA_VERSION=12.4
# Automatically set by buildx
ARG TARGETPLATFORM

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        build-essential \
        ca-certificates \
        ccache \
        curl \
        git && \
    rm -rf /var/lib/apt/lists/*

# Install uv (build library)
COPY --from=ghcr.io/astral-sh/uv:0.5.31 /uv /uvx /bin/
ENV PATH="$PATH:/root/.local/bin"

# Install python and pytorch
RUN uv python install ${PYTHON_VERSION}
RUN uv venv --python ${PYTHON_VERSION} && uv pip install torch==${PYTORCH_VERSION} pip setuptools packaging
ENV VIRTUAL_ENV=/usr/src/.venv/
ENV PATH="$PATH:/usr/src/.venv/bin/"

# CUDA kernels builder image
FROM pytorch-install AS kernel-builder

ARG MAX_JOBS=2
ENV TORCH_CUDA_ARCH_LIST="8.0;8.6;9.0+PTX"

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        ninja-build cmake && \
    rm -rf /var/lib/apt/lists/*

# Build Flash Attention CUDA kernels
FROM kernel-builder AS flash-att-builder
WORKDIR /usr/src
COPY --from=tgi /tgi/server/Makefile-flash-att Makefile
# Build specific version of flash attention
RUN . .venv/bin/activate && make build-flash-attention

# Build Flash Attention v2 CUDA kernels
FROM kernel-builder AS flash-att-v2-builder
WORKDIR /usr/src
COPY --from=tgi /tgi/server/Makefile-flash-att-v2 Makefile
# Build specific version of flash attention v2
RUN . .venv/bin/activate && make build-flash-attention-v2-cuda

# Build Transformers exllama kernels
FROM kernel-builder AS exllama-kernels-builder
WORKDIR /usr/src
COPY --from=tgi /tgi/server/exllama_kernels/ .
RUN . .venv/bin/activate && python setup.py build

# Build Transformers exllama kernels
FROM kernel-builder AS exllamav2-kernels-builder
WORKDIR /usr/src
COPY --from=tgi /tgi/server/Makefile-exllamav2/ Makefile
# Build specific version of transformers
RUN . .venv/bin/activate && make build-exllamav2

# Build Transformers awq kernels
FROM kernel-builder AS awq-kernels-builder
WORKDIR /usr/src
COPY --from=tgi /tgi/server/Makefile-awq Makefile
# Build specific version of transformers
RUN . .venv/bin/activate && make build-awq

# Build eetq kernels
FROM kernel-builder AS eetq-kernels-builder
WORKDIR /usr/src
COPY --from=tgi /tgi/server/Makefile-eetq Makefile
# Build specific version of transformers
RUN . .venv/bin/activate && make build-eetq

# Build Lorax Punica kernels
FROM kernel-builder AS lorax-punica-builder
WORKDIR /usr/src
COPY --from=tgi /tgi/server/Makefile-lorax-punica Makefile
# Build specific version of transformers
RUN . .venv/bin/activate && TORCH_CUDA_ARCH_LIST="8.0;8.6+PTX" make build-lorax-punica

# Build Transformers CUDA kernels
FROM kernel-builder AS custom-kernels-builder
WORKDIR /usr/src
COPY --from=tgi /tgi/server/custom_kernels/ .
# Build specific version of transformers
RUN . .venv/bin/activate && python setup.py build

# Build mamba kernels
FROM kernel-builder AS mamba-builder
WORKDIR /usr/src
COPY --from=tgi /tgi/server/Makefile-selective-scan Makefile
RUN . .venv/bin/activate && make build-all

# Build flashinfer
FROM kernel-builder AS flashinfer-builder
WORKDIR /usr/src
COPY --from=tgi /tgi/server/Makefile-flashinfer Makefile
RUN . .venv/bin/activate && make install-flashinfer

# Text Generation Inference base image
FROM nvidia/cuda:12.4.0-base-ubuntu22.04 AS base

# Text Generation Inference base env
ENV HF_HOME=/tmp \
    HF_HUB_ENABLE_HF_TRANSFER=1 \
    PORT=8080

WORKDIR /usr/src

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        libssl-dev \
        ca-certificates \
        make \
        curl \
        git && \
    rm -rf /var/lib/apt/lists/*

RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV PATH="$PATH:/root/.local/bin"
# Install flash-attention dependencies
# RUN pip install einops --no-cache-dir

# Copy env with PyTorch installed
COPY --from=pytorch-install /usr/src/.venv /usr/src/.venv
ENV PYTHON_VERSION=3.11
RUN uv python install ${PYTHON_VERSION}
ENV VIRTUAL_ENV=/usr/src/.venv/
ENV PATH="$PATH:/usr/src/.venv/bin/"

# Copy build artifacts from flash attention builder
COPY --from=flash-att-builder /usr/src/flash-attention/build/lib.linux-x86_64-cpython-311 /usr/src/.venv/lib/python3.11/site-packages
COPY --from=flash-att-builder /usr/src/flash-attention/csrc/layer_norm/build/lib.linux-x86_64-cpython-311 /usr/src/.venv/lib/python3.11/site-packages
COPY --from=flash-att-builder /usr/src/flash-attention/csrc/rotary/build/lib.linux-x86_64-cpython-311 /usr/src/.venv/lib/python3.11/site-packages
# Copy build artifacts from flash attention v2 builder
COPY --from=flash-att-v2-builder /usr/src/.venv/lib/python3.11/site-packages/flash_attn_2_cuda.cpython-311-x86_64-linux-gnu.so /usr/src/.venv/lib/python3.11/site-packages
# Copy build artifacts from custom kernels builder
COPY --from=custom-kernels-builder /usr/src/build/lib.linux-x86_64-cpython-311 /usr/src/.venv/lib/python3.11/site-packages
# Copy build artifacts from exllama kernels builder
COPY --from=exllama-kernels-builder /usr/src/build/lib.linux-x86_64-cpython-311 /usr/src/.venv/lib/python3.11/site-packages
# Copy build artifacts from exllamav2 kernels builder
COPY --from=exllamav2-kernels-builder /usr/src/exllamav2/build/lib.linux-x86_64-cpython-311 /usr/src/.venv/lib/python3.11/site-packages
# Copy build artifacts from awq kernels builder
COPY --from=awq-kernels-builder /usr/src/llm-awq/awq/kernels/build/lib.linux-x86_64-cpython-311 /usr/src/.venv/lib/python3.11/site-packages
# Copy build artifacts from eetq kernels builder
COPY --from=eetq-kernels-builder /usr/src/eetq/build/lib.linux-x86_64-cpython-311 /usr/src/.venv/lib/python3.11/site-packages
# Copy build artifacts from lorax punica kernels builder
COPY --from=lorax-punica-builder /usr/src/lorax-punica/server/punica_kernels/build/lib.linux-x86_64-cpython-311 /usr/src/.venv/lib/python3.11/site-packages
# Copy build artifacts from mamba builder
COPY --from=mamba-builder /usr/src/mamba/build/lib.linux-x86_64-cpython-311/ /usr/src/.venv/lib/python3.11/site-packages
COPY --from=mamba-builder /usr/src/causal-conv1d/build/lib.linux-x86_64-cpython-311/ /usr/src/.venv/lib/python3.11/site-packages
# Copy build artifacts from flashinfer builder
COPY --from=flashinfer-builder /usr/src/.venv/lib/python3.11/site-packages/flashinfer/ /usr/src/.venv/lib/python3.11/site-packages/flashinfer/

# Install flash-attention dependencies
# RUN pip install einops --no-cache-dir # Commented out in git but no reason given

# Install server
COPY --from=tgi /tgi/proto proto
COPY --from=tgi /tgi/server server
ENV HF_KERNELS_CACHE=/kernels

RUN cd server && \
    uv sync --frozen --extra gen --extra attention --extra bnb --extra accelerate --extra compressed-tensors --extra marlin --extra moe --extra quantize --extra peft --extra outlines --no-install-project --active && \
    make gen-server-raw && \
    hf-kernels download .

RUN cd server && \
    uv sync --frozen --extra gen --extra attention --extra bnb --extra accelerate --extra compressed-tensors --extra marlin --extra moe --extra quantize --extra peft --extra outlines --active --python=${PYTHON_VERSION} && \
    uv pip install nvidia-nccl-cu12==2.25.1 && \
    pwd && \
    text-generation-server --help

# ENV LD_PRELOAD=/opt/conda/lib/python3.11/site-packages/nvidia/nccl/lib/libnccl.so.2
# Required to find libpython within the rust binaries
ENV LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/root/.local/share/uv/python/cpython-3.11.11-linux-x86_64-gnu/lib/"
# This is needed because exl2 tries to load flash-attn
# And fails with our builds.
ENV EXLLAMA_NO_FLASH_ATTN=1

# Deps before the binaries
# The binaries change on every build given we burn the SHA into them
# The deps change less often.
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        build-essential \
        g++ && \
    rm -rf /var/lib/apt/lists/*

# Install benchmarker
COPY --from=builder /usr/src/target/release-opt/text-generation-benchmark /usr/local/bin/text-generation-benchmark
# Install router
COPY --from=builder /usr/src/target/release-opt/text-generation-router /usr/local/bin/text-generation-router
# Install launcher
COPY --from=builder /usr/src/target/release-opt/text-generation-launcher /usr/local/bin/text-generation-launcher


# Final image
FROM base

RUN uv pip install google-crc32c

# Install Google CLI single command
RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" \
    | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && \
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg \
    | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add - && \
    apt-get update -y && \
    apt-get install google-cloud-sdk -y


# COPY custom entrypoint for Google
COPY --chmod=775 ./containers/tgi/gpu/3.1.1/entrypoint.sh entrypoint.sh
ENTRYPOINT ["./entrypoint.sh"]
```

**Comment by liuteng** [comment]
I also meet this issue in sglang:

CUDA Error: an illegal memory access was encountered (CUDA Error: 700an illegal memory access was encountered) (/opt/conda/lib/python3.10/site-packages/flashinfer/data/include/flashinfer/attention/prefill.cuh700: line ) 2349/opt/conda/lib/python3.10/site-packages/flashinfer/data/include/flashinfer/attention/prefill.cuh at function cudaLaunchKernel((void*)kernel, nblks, nthrs, args, smem_size, stream): line 2349
at function cudaLaunchKernel((void*)kernel, nblks, nthrs, args, smem_size, stream)
[2025-04-22 15:12:46 TP0] Scheduler hit an exception: Traceback (most recent call last):
File "/opt/conda/lib/python3.10/site-packages/sglang/srt/managers/scheduler.py", line 2011, in run_scheduler_process
scheduler.event_loop_normal()
File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
return func(*args, **kwargs)
File "/opt/conda/lib/python3.10/site-packages/sglang/srt/managers/scheduler.py", line 619, in event_loop_normal
result = self.run_batch(batch)
File "/opt/conda/lib/python3.10/site-packages/sglang/srt/managers/scheduler.py", line 1367, in run_batch
) = self.draft_worker.forward_batch_speculative_generation(batch)
File "/opt/conda/lib/python3.10/site-packages/sglang/srt/speculative/eagle_worker.py", line 258, in forward_batch_speculative_generation
logits_output, verify_output, model_worker_batch = self.verify(
File "/opt/conda/lib/python3.10/site-packages/sglang/srt/speculative/eagle_worker.py", line 485, in verify
logits_output, _ = self.target_worker.forward_batch_generation(
File "/opt/conda/lib/python3.10/site-packages/sglang/srt/managers/tp_worker.py", line 176, in forward_batch_generation
logits_output = self.model_runner.forward(forward_batch)
File "/opt/conda/lib/python3.10/site-packages/sglang/srt/model_executor/model_runner.py", line 1032, in forward
return self.forward_extend(
File "/opt/conda/lib/python3.10/site-packages/sglang/srt/model_executor/model_runner.py", line 993, in forward_extend
return self.model.forward(
File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
return func(*args, **kwargs)
File "/opt/conda/lib/python3.10/site-packages/sglang/srt/models/qwen2.py", line 383, in forward
hidden_states = self.model(input_ids, positions, forward_batch, input_embeds)
File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
return forward_call(*args, **kwargs)
File "/opt/conda/lib/python3.10/site-packages/sglang/srt/models/qwen2.py", line 291, in forward
hidden_states, residual = layer(
File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
return forward_call(*args, **kwargs)
File "/opt/conda/lib/python3.10/site-packages/sglang/srt/models/qwen2.py", line 224, in forward
hidden_states = self.self_attn(
File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
return forward_call(*args, **kwargs)
File "/opt/conda/lib/python3.10/site-packages/sglang/srt/models/qwen2.py", line 170, in forward
attn_output = self.attn(q, k, v, forward_batch)
File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
return forward_call(*args, **kwargs)
File "/opt/conda/lib/python3.10/site-packages/sglang/srt/layers/radix_attention.py", line 97, in forward
return forward_batch.attn_backend.forward(
File "/opt/conda/lib/python3.10/site-packages/sglang/srt/layers/attention/base_attn_backend.py", line 77, in forward
return self.forward_extend(
File "/opt/conda/lib/python3.10/site-packages/sglang/srt/layers/attention/flashinfer_backend.py", line 420, in forward_extend
o = prefill_wrapper_paged.forward(
File "/opt/conda/lib/python3.10/site-packages/flashinfer/prefill.py", line 1496, in forward
return self.run(q, paged_kv_cache, k_scale=k_scale, v_scale=v_scale)
File "/opt/conda/lib/python3.10/site-packages/flashinfer/prefill.py", line 1679, in run
self._cached_module.paged_run(*run_args)
File "/opt/conda/lib/python3.10/site-packages/flashinfer/prefill.py", line 346, in paged_run
paged_run_func(
File "/opt/conda/lib/python3.10/site-packages/torch/_ops.py", line 1123, in call
return self._op(*args, **(kwargs or {}))
File "/opt/conda/lib/python3.10/site-packages/torch/utils/_device.py", line 104, in torch_function
return func(*args, **kwargs)
File "/opt/conda/lib/python3.10/site-packages/torch/_ops.py", line 1123, in call
return self._op(*args, **(kwargs or {}))
RuntimeError: BatchPrefillWithPagedKVCache failed with error an illegal memory access was encountered

**Comment by Cheng-Logic** [comment]
The illegal memory access occurs during BatchPrefillWithPagedKVCache when launched on a non-default CUDA device (e.g., cuda:1), because FlashInfer implicitly assumes device 0 or fails to synchronize the stream on the correct active device before executing the kernel.
```C++
// Fix in include/flashinfer/attention/prefill.cuh
template <typename T>
cudaError_t BatchPrefillWithPagedKVCache(...) {
    // ... setup code ...
    
    // Explicitly set the device before launching the kernel
    int device;
    cudaGetDevice(&device);
    cudaSetDevice(device);

    cudaLaunchKernel((void*)kernel, nblks, nthrs, args, smem_size, stream);
    
    // ...
}
```

**Comment by saltyminty** [comment]
This issue has been fixed in later versions of FlashInfer (likely during one of the API redesigns) and is currently not reproducible in v0.6.4. Marking closed – please reopen if you're still running into this.
